
name: grayround project

on:
  push:
    branches:
      - 'master'
    tags:
      - '**'
      
jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Get current date
        id: get_date
        run: |
          echo $("%Y%m%d")
          
      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: haeunmoon/grayround
          tag-semver: |
            {{  steps.get_date.outputs.date  }}
            {{major}}.{{minor}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: haeunmoon/grayround:{{ steps.get_date.outputs.date }}
          labels: ${{ steps.docker_meta.outputs.labels }}
